Shop1503/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls'))
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from shop.views import *


urlpatterns = [
    path('', index, name='home_page'),
    path('getProducts/', query_all, name='catalog_products_page'),
    path('getProduct/<int:id>', get_one_product),
    path('product/<int:id>', detail_product, name='detail_page'),
    path('createProduct/', create_product),
    path('getSuppliers/', get_suppliers, name='suppliers_page'),
    path('createSupplier', create_supplier, name='create_supplier_page'),
    path('supplier/<int:id>', detail_supplier, name='detail_supplier_page'),
    path('register/', user_registration, name='registration_page'),
    path('auth/', user_login, name='user_login_page'),
    path('logout/', user_logout, name='logout'),
    path('anon/', anon, name='anon'),
    path('auth/', auth, name='auth'),
    path('can_add/', is_able_to_add_product, name='add'),
    path('can_add_change/', is_able_to_add_and_change_product, name='add_change'),
    path('can_change_delivery_type', is_able_to_change_delivery_type, name='change_delivery_type'),
    path('category/', CategoryList.as_view(), name='category_list'),
    path('category/create', CategoryCreate.as_view(), name='category_create'),
    path('category/<int:pk>/detail/', CategoryDetail.as_view(), name='category_detail'),
    path('category/<int:pk>/update/', CategoryUpdate.as_view(), name='category_update'),
    path('category/<int:pk>/delete/', CategoryDelete.as_view(), name='category_delete'),
    path('contact/', contact_email, name='email_page'),
    path('api/', test_json, name='api_test'),
    path('api/orders/', order_api_list, name='api_order_list'),
    path('api/orders/<int:pk>/', order_api_detail, name='api_order_detail'),
]

from rest_framework import routers

router = routers.SimpleRouter()
router.register(r'api/products', ProductViewSet, basename='product')

urlpatterns += router.urls

shop/models.py
from django.db import models
from django.urls import reverse_lazy
MAX_LENGTH_CHAR = 255

class Supplier(models.Model):
    name = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Название')
    representor_surname = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Фамилия представителя')
    representor_name = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Имя представителя')
    representor_patronymic = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Отчество представителя')
    representor_phone_number = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Телефон представителя')
    address = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Адрес')
    isActive = models.BooleanField(default=True, verbose_name='Существует ли?')

    def __str__(self):
        return (f"{self.name}, представитель: {self.representor_surname} {self.representor_name}"
                f" {self.representor_patronymic}, телефон: {self.representor_phone_number}")

    class Meta:
        verbose_name = 'Поставщик'
        verbose_name_plural = 'Поставщики'

class Supply(models.Model):
    date = models.DateTimeField(verbose_name='Дата поставки')

    supplier = models.ForeignKey(Supplier, on_delete=models.PROTECT, verbose_name='Поставщик')
    product = models.ManyToManyField('Product', through='Pos_supply', verbose_name='Товар')

    def __str__(self):
        return f"{self.pk} - {self.date}, название компании-поставщика: {self.supplier.name}"

    class Meta:
        verbose_name = 'Поставка'
        verbose_name_plural = 'Поставки'

class Pos_supply(models.Model):
    product = models.ForeignKey('Product', on_delete=models.PROTECT, verbose_name='Товар')
    supply = models.ForeignKey(Supply, on_delete=models.PROTECT, verbose_name='Поставка')

    quantity = models.PositiveIntegerField(verbose_name='Количество товара')

    def __str__(self):
        return f"{self.product.name} - {self.supply.pk}"

    class Meta:
        verbose_name = 'Позиция поставки'
        verbose_name_plural = 'Позиции поставок'


class Tag(models.Model):
    name = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Название')
    description = models.TextField(null=True, blank=True, verbose_name='Описание')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'


class Category(models.Model):
    name = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Название')
    description = models.TextField(null=True, blank=True, verbose_name='Описание')

    def get_absolute_url(self):
        return reverse_lazy('category_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Order(models.Model):
    SHOP = "SH"
    COURIER = "CR"
    PICKUPPOINT = "PP"

    TYPE_OF_DELIVERY = [
        (SHOP, "Магазин"),
        (COURIER, "Курьер"),
        (PICKUPPOINT, "Пункт выдачи")
    ]

    customer_surname = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Фамилия покупателя')
    customer_name = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Имя покупателя')
    customer_patronymic = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Отчество покупателя')
    delivery_address = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Адрес доставки')
    delivery_type = models.CharField(max_length=2, choices=TYPE_OF_DELIVERY, default=SHOP, verbose_name='Способ доставки')
    creation_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    finish_date = models.DateTimeField(null=True, blank=True, verbose_name='Дата создания')

    product = models.ManyToManyField('Product', through='Pos_order', verbose_name='Товар')

    def __str__(self):
        return f"{self.pk}: {self.customer_surname} {self.customer_name} {self.customer_patronymic}, {self.creation_date}"

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'
        permissions = [
            ('change_delivery_type', 'Возможность изменить тип доставки'),
        ]

from shop.utils import sum_price_count
class Pos_order(models.Model):
    product = models.ForeignKey('Product', on_delete=models.PROTECT, verbose_name='Товар')
    order = models.ForeignKey(Order, on_delete=models.PROTECT, verbose_name='Заказ')
    quantity = models.PositiveIntegerField(default=1,verbose_name='Количество товара')
    discount = models.PositiveIntegerField(default=0, verbose_name='Скидка')

    def __str__(self):
        return f"{self.pk} - {self.product.name}, {self.order.customer_surname} {self.order.customer_name} {self.order.customer_patronymic}"

    def sum_pos_order(self):
        return sum_price_count(self.product.price, self.quantity, self.discount)

    class Meta:
        verbose_name = 'Позиция заказа'
        verbose_name_plural = 'Позиции заказов'

class Parameter(models.Model):
    name = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Название')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Характеристика'
        verbose_name_plural = 'Характеристики'

class Pos_parameter(models.Model):
    product = models.ForeignKey('Product', on_delete=models.PROTECT, verbose_name='Товар')
    parameter = models.ForeignKey(Parameter, on_delete=models.PROTECT, verbose_name='Характеристика')
    value = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Значение характеристики')


    def __str__(self):
        return f"{self.product.name} - {self.value}"

    class Meta:
        verbose_name = 'Позиция характеристики'
        verbose_name_plural = 'Позиции характеристик'

class Product(models.Model):
    name = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Название')
    description = models.TextField(null=True, blank=True, verbose_name='Описание')
    price = models.FloatField(verbose_name='Цена')
    creation_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')
    image = models.ImageField(upload_to='image/%Y/%m/%d', null=True, blank=True, verbose_name='Картинка')
    isActive = models.BooleanField(default=True, verbose_name='Существует ли?')

    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    tag = models.ManyToManyField(Tag, blank=True, null=True)
    parameter = models.ManyToManyField(Parameter, through=Pos_parameter)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

shop/forms.py
import re
from django.core.exceptions import ValidationError
from django import forms
from shop.models import *

class SupplierForm(forms.ModelForm):
    class Meta:
        model = Supplier
        fields = (
            'name',
            'representor_surname',
            'representor_name',
            'representor_patronymic',
            'representor_phone_number',
            'address'
        )
    def clean_representor_phone_number(self):
        representor_phone_number = self.cleaned_data['representor_phone_number']
        if re.match(r'\+7\(\d{3}\)\d{3}-\d{2}-\d{2}', representor_phone_number):
            return representor_phone_number
        raise ValidationError('Телефон должен быть прописан в формате +7(___)___-__-__')

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = (
            'name',
            'description'
        )

from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2', 'email']

    username = forms.CharField(
        label='Логин',
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        min_length=2
    )
    email = forms.CharField(
        label='Адрес электронной почты',
        widget=forms.EmailInput(attrs={'class': 'form-control'})
    )
    password1 = forms.CharField(
        label='Придумайте пароль',
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )
    password2 = forms.CharField(
        label='Подтвердите пароль',
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )

class LoginForm(AuthenticationForm):
    username = forms.CharField(
        label='Логин',
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        min_length=2
    )
    password = forms.CharField(
        label='Пароль',
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )

class ContactForm(forms.Form):
    subject = forms.CharField(
        label='Заголовок письма',
        widget=forms.TextInput(
            attrs={'class': 'form-control',},
        ),
    )
    content = forms.CharField(
        label='Текст письма',
        widget=forms.Textarea(
            attrs={'class': 'form-control', 'rows': 11,}
        )
    )

shop/templates/queries/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title_block %}
    {{ obj.name }}
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-2">
            <div class="container">
                <h1>Название: {{ obj.name }}</h1>
                <p>Описание: {{ obj.description }}</p>
                <h3>Цена: {{ obj.price }}</h3>
            </div>
        </div>
        <div class="col-3">
            {% if obj.image %}
                <img src="{{ obj.image.url }}" class="card-img-top" alt="...">
            {% else %}
                <img src="{% static 'shop/image/98094191.jpg' %}" class="card-img-top" alt="...">
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="container">
            <h2>Категория</h2>
            <a href="#">{{ obj.category.name }}</a>
        </div>
    </div>

    <div class="row">
        <div class="container">
            <h3>Теги:</h3>
            {% for tag in obj.tag.all %}
                {{ tag.name }}
            {% endfor %}
        </div>
    </div>
    <div class="row">
        <h3>Характеристики</h3>
        {% for param in obj.pos_parameter_set.all %}
            <div class="col-4">{{ param.parameter }} : {{ param.value }}</div>
        {% endfor %}
    </div>
    {% if request.user.is_authenticated %}
        <p><input type="submit" class="btn btn-success" value="Купить"></p>
    {% endif %}
    {% if request.user.is_staff %}
        <div class="row">
            <h1>Заказы, в которых участвовал товар</h1>
            {% for order in obj.order_set.all %}
                Номер заказа: {{ order.pk }}
            {% endfor %}
        </div>
    {% endif %}
    <div class="row">
        <h2>Поставки:</h2>
        {% for supply in obj.supply_set.all %}
            <ul>
                <li>{{ supply }}</li>
            </ul>
        {% endfor %}
    </div>
    <p><a href="{% url 'home_page' %}">На стартовую страницу</a></p>
</div>
{% endblock %}

shop/templates/queries/index.html
{% extends 'base.html' %}
{% block title_block %}
    Домашняя страница
{% endblock %}

{% block content %}
    {% if perms.shop.add_product %}
        <h4>Можешь добавлять товар</h4>
    {% endif %}
    {% if perms.shop.add_product and perms.shop.change_product %}
        <h4>Можешь добавлять и редактировать товар</h4>
    {% endif %}
    {% if perms.shop.change_delivery_type %}
        <h4>Можешь редактировать способ доставки</h4>
    {% endif %}
{% endblock %}

shop/templates/queries/message.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Сообщение</title>
</head>
<body>

    <h1>{{ message }}</h1>

</body>
</html>

shop/templates/queries/purchase.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Товар успешно куплен</title>
</head>
<body>

<h1>Товар успешно куплен</h1>

</body>
</html>

shop/templates/queries/query_all.html
{% extends 'base.html' %}
{% load static %}
{% block title_block %}
    Все товары
{% endblock %}
{% block content %}

    {% if request.user.is_staff%}
        <a href="{% url 'create_supplier_page' %}" class="btn btn-outline-success">Добавить поставщика</a>
    {% endif %}
    <div class="container">
        <div class="row">
            {% for obj in list %}
                <div class="col-4">
                    <div class="card" style="width: 18rem;">
                        {% if obj.image %}
                        <img src="{{ obj.image.url }}" class="card-img-top" alt="...">
                        {% else %}
                        <img src="{% static 'shop/image/98094191.jpg' %}" class="card-img-top" alt="...">
                        {% endif %}
                    <div class="card-body">
                        <h5 class="card-title"> {{ obj.name }}</h5>
                        <h6 class="card-subtitle mb-2 text-body-secondary"> Категория: {{ obj.category.name }}</h6>
                        <p class="card-text">{{ obj.description }}</p>
                        <p class="card-text">Цена: {{ obj.price }}</p>
                        <a href="{% url 'detail_page' obj.pk %}" class=" btn btn-primary">Подробнее</a>
                    </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

shop/templates/queries/query_one.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Товар</title>
</head>
<body>
    <h1>Один товар:</h1>
    <h3>Название: {{ obj.name }}</h3>
    <h3>ID: {{ obj.pk }}</h3>
    <h3>Описание: {{ obj.description }}</h3>
    <h3>Цена: {{ obj.price }}</h3>
    <h3>Категория: {{ obj.category.name }}</h3>
</body>
</html>